<a href="https://colab.research.google.com/github/2005monicagarcia-arch/FinDataSets/blob/main/01_download_yfinance_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import yfinance as yf
import pandas as pd

tickers = ["AAPL", "MSFT", "NVDA", "SPY", "QQQ", "VOO", "TLT", "IEF"]

data = yf.download(
    tickers,
    start="2016-01-01",
    end="2026-06-30",
    auto_adjust=False
)

data.head()

[*********************100%***********************]  8 of 8 completed

Price       Adj Close                                                          \
Ticker           AAPL        IEF       MSFT      NVDA         QQQ         SPY
Date
2016-01-04  23.709105  83.766731  47.770718  0.788626  101.605606  169.471542
2016-01-05  23.114971  83.743057  47.988647  0.801295  101.429306  169.758163
2016-01-06  22.662621  84.248596  47.116909  0.768161  100.455032  167.616852
2016-01-07  21.706150  84.430290  45.478077  0.737708   97.309418  163.595413
2016-01-08  21.820925  84.643555  45.617546  0.721872   96.511421  161.799728

Price                                  Close              ...        Open  \
Ticker            TLT         VOO       AAPL         IEF  ...         TLT
Date                                                      ...
2016-01-04  90.984581  154.629593  26.337500  106.040001  ...  121.930000
2016-01-05  90.617508  154.906433  25.677500  106.010002  ...  120.879997
2016-01-06  91.838615  152.943268  25.174999  106.650002  ...  122.300003
2016-01-07  92.003433  149.218277  24.112499  106.879997  ...  122.680000
2016-01-08  92.415466  147.632645  24.240000  107.150002  ...  122.430000

Price                      Volume                                          \
Ticker             VOO       AAPL      IEF      MSFT       NVDA       QQQ
Date
2016-01-04  183.770004  270597600  6183700  53778000  358076000  50807600
2016-01-05  184.570007  223164000  2122800  34079700  490272000  38795200
2016-01-06  181.929993  273829600  1906100  39518900  449344000  41891100
2016-01-07  179.149994  324377600  3106000  56564900  645304000  61386300
2016-01-08  178.970001  283192000  1783200  48754000  398472000  69344000

Price
Ticker            SPY       TLT      VOO
Date
2016-01-04  222353500  10591900  4193500
2016-01-05  110845800   6242600  2882500
2016-01-06  152112600   8916900  2755100
2016-01-07  213436100  10202200  4952500
2016-01-08  209817200   9577200  7357300

[5 rows x 48 columns]

In [ ]:
data.to_csv("portfolio_dataset_2016_2026.csv")

In [ ]:
from google.colab import files

files.download("portfolio_dataset_2016_2026.csv")

In [ ]:
import yfinance as yf
import pandas as pd

tickers = ["AAPL", "MSFT", "NVDA", "SPY", "QQQ", "VOO", "TLT", "IEF"]

data = yf.download(
    tickers,
    start="2006-01-01",
    end="2026-06-30",
    auto_adjust=False
)

data.head()

[*********************100%***********************]  8 of 8 completed

Price      Adj Close                                                        \
Ticker          AAPL        IEF       MSFT      NVDA        QQQ        SPY
Date
2006-01-03  2.237674  49.090782  18.632084  0.291656  35.273769  87.000923
2006-01-04  2.244259  49.178562  18.722326  0.299822  35.640938  87.412926
2006-01-05  2.226598  49.190250  18.736208  0.306613  35.794628  87.467842
2006-01-06  2.284072  49.125877  18.680679  0.311649  36.443577  88.195724
2006-01-09  2.276589  49.149277  18.645964  0.320348  36.588741  88.422325

Price                         Close             ...       Open         Volume  \
Ticker            TLT VOO      AAPL        IEF  ...        TLT VOO       AAPL
Date                                            ...
2006-01-03  47.859772 NaN  2.669643  83.900002  ...  91.589996 NaN  807234400
2006-01-04  47.974483 NaN  2.677500  84.050003  ...  91.540001 NaN  619603600
2006-01-05  47.917126 NaN  2.656429  84.070000  ...  91.879997 NaN  449422400
2006-01-06  47.828453 NaN  2.725000  83.959999  ...  91.769997 NaN  704457600
2006-01-09  47.859772 NaN  2.716071  84.000000  ...  91.699997 NaN  675040800

Price
Ticker         IEF       MSFT       NVDA        QQQ       SPY      TLT VOO
Date
2006-01-03  299500   79973000  472812000  109350400  73256700  1392700 NaN
2006-01-04  112300   57975600  510072000   92769400  51899600   387600 NaN
2006-01-05  159700   48245500  646092000   77656900  47307500   453400 NaN
2006-01-06  179100  100963000  623388000  110053900  62885900  1193700 NaN
2006-01-09   78600   55625000  560484000   80768800  43527400   413600 NaN

[5 rows x 48 columns]

In [ ]:
data.to_csv("portfolio_dataset_2006_2026.csv")

In [ ]:
from google.colab import files
files.download("portfolio_dataset_2006_2026.csv")

In [ ]:
import yfinance as yf
import pandas as pd

tickers = ["AAPL", "MSFT", "NVDA", "SPY", "QQQ", "TLT", "IEF"]

data = yf.download(
    tickers,
    start="2006-01-01",
    end="2026-06-30",
    auto_adjust=False
)

data.head()

[*********************100%***********************]  7 of 7 completed

Price      Adj Close                                                        \
Ticker          AAPL        IEF       MSFT      NVDA        QQQ        SPY
Date
2006-01-03  2.237673  49.090813  18.632084  0.291656  35.273769  87.000908
2006-01-04  2.244259  49.178551  18.722328  0.299822  35.640934  87.412918
2006-01-05  2.226598  49.190231  18.736214  0.306612  35.794636  87.467857
2006-01-06  2.284073  49.125893  18.680685  0.311649  36.443584  88.195740
2006-01-09  2.276588  49.149277  18.645973  0.320348  36.588745  88.422348

Price                     Close                        ...       Open  \
Ticker            TLT      AAPL        IEF       MSFT  ...        QQQ
Date                                                   ...
2006-01-03  47.859772  2.669643  83.900002  26.840000  ...  40.650002
2006-01-04  47.974487  2.677500  84.050003  26.969999  ...  41.410000
2006-01-05  47.917107  2.656429  84.070000  26.990000  ...  41.750000
2006-01-06  47.828461  2.725000  83.959999  26.910000  ...  42.259998
2006-01-09  47.859772  2.716071  84.000000  26.860001  ...  42.680000

Price                                 Volume                                \
Ticker             SPY        TLT       AAPL     IEF       MSFT       NVDA
Date
2006-01-03  125.190002  91.589996  807234400  299500   79973000  472812000
2006-01-04  126.860001  91.540001  619603600  112300   57975600  510072000
2006-01-05  127.150002  91.879997  449422400  159700   48245500  646092000
2006-01-06  128.020004  91.769997  704457600  179100  100963000  623388000
2006-01-09  128.419998  91.699997  675040800   78600   55625000  560484000

Price
Ticker            QQQ       SPY      TLT
Date
2006-01-03  109350400  73256700  1392700
2006-01-04   92769400  51899600   387600
2006-01-05   77656900  47307500   453400
2006-01-06  110053900  62885900  1193700
2006-01-09   80768800  43527400   413600

[5 rows x 42 columns]

In [ ]:
data.to_csv("SPY_portfolio_dataset_2006_2026.csv")

In [ ]:
from google.colab import files
files.download("SPY_portfolio_dataset_2006_2026.csv")

In [ ]:
import yfinance as yf
import pandas as pd

# Time period: 20 years
start_date = "2006-01-01"
end_date = "2026-06-30"

# Original tickers without VOO
base_tickers = ["AAPL", "MSFT", "NVDA", "SPY", "QQQ", "TLT", "IEF"]

# Option 1: Global Hard-Asset Blend
# Add international stocks + real estate
option1_tickers = base_tickers + ["EFA", "VNQ"]

# Option 2: Core Domestic Value Tilt
# Add financials + energy
option2_tickers = base_tickers + ["XLF", "XLE"]


# Function to download dataset
def download_dataset(tickers, file_name):
    data = yf.download(
        tickers,
        start=start_date,
        end=end_date,
        auto_adjust=False
    )

    # Save full dataset
    data.to_csv(file_name)

    print(f"\nDownloaded: {file_name}")
    print(f"Tickers: {tickers}")
    print(f"Shape: {data.shape}")

    # Check missing values for Adjusted Close
    adj_close = data["Adj Close"]
    print("\nMissing values in Adjusted Close:")
    print(adj_close.isna().sum())

    return data


# Download Option 1
data_option1 = download_dataset(
    option1_tickers,
    "portfolio_option1_EFA_VNQ_20years.csv"
)

# Download Option 2
data_option2 = download_dataset(
    option2_tickers,
    "portfolio_option2_XLF_XLE_20years.csv"
)

[*********************100%***********************]  9 of 9 completed
[                       0%                       ]

Downloaded: portfolio_option1_EFA_VNQ_20years.csv
Tickers: ['AAPL', 'MSFT', 'NVDA', 'SPY', 'QQQ', 'TLT', 'IEF', 'EFA', 'VNQ']
Shape: (5153, 54)

Missing values in Adjusted Close:
Ticker
AAPL    0
EFA     0
IEF     0
MSFT    0
NVDA    0
QQQ     0
SPY     0
TLT     0
VNQ     0
dtype: int64

[*********************100%***********************]  9 of 9 completed

Downloaded: portfolio_option2_XLF_XLE_20years.csv
Tickers: ['AAPL', 'MSFT', 'NVDA', 'SPY', 'QQQ', 'TLT', 'IEF', 'XLF', 'XLE']
Shape: (5153, 54)

Missing values in Adjusted Close:
Ticker
AAPL    0
IEF     0
MSFT    0
NVDA    0
QQQ     0
SPY     0
TLT     0
XLE     0
XLF     0
dtype: int64

In [ ]:
from google.colab import files
files.download("portfolio_option1_EFA_VNQ_20years.csv")

In [ ]:
from google.colab import files
files.download("portfolio_option2_XLF_XLE_20years.csv")